version: "3.8"
services:
    web:
        build: ./app
        image: 484063240365.dkr.ecr.us-east-2.amazonaws.com/django_docker_aws_web
    pg:
        container_name: pg_container
        image: postgres:13.2-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_HOST_AUTH_METHOD: trust
            PGUSER: postgres
        ports:
            - "5432:5432"
        volumes:
            - "${PWD}/data/misc/init.sql:/docker-entrypoint-initdb.d/1-init.sql"
            - "${PWD}/data/northwind/init.sql:/docker-entrypoint-initdb.d/2-ini\
              t.sql"
            - "${PWD}/data/moma/init.sql:/docker-entrypoint-initdb.d/3-init.sql"
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:5.2
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin123
            PGADMIN_LISTEN_PORT: 5433
            PGADMIN_CONFIG_SERVER_MODE: "False"
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
            PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
        ports:
            - "5433:5433"
        depends_on:
            - pg
    nginx:
        build: ./nginx
        image: 484063240365.dkr.ecr.us-east-2.amazonaws.com/django_docker_aws_nginx
networks:
    default:
        name: nunet
